version: 0.0
os: linux
hooks:
    BeforeBlockTraffic:
        - location: before_block_traffic.sh
    AfterBlockTraffic:
        - location: after_block_traffic.sh
    ApplicationStop:
        - location: application_stop.sh
    BeforeInstall:
        - location: before_install.sh
    AfterInstall:
        - location: after_install.sh
    ApplicationStart:
        - location: application_start.sh
    ValidateService:
        - location: validate_service.sh
    BeforeAllowTraffic:
        - location: before_allow_traffic.sh
    AfterAllowTraffic:
        - location: after_allow_traffic.sh
